version: '3'

services:
  php-fpm:
    build: ./docker/php-fpm
    tty: true
    volumes:
      - ../:/workspace:cached
      - php-socket:/var/run/php
  mariadb:
    build: ./docker/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: tutorial
      MARIADB_DATABASE: tutorial
      MARIADB_USER: tutorial
      MARIADB_PASSWORD: tutorial
      MARIADB_HOST: mariadb
volumes:
  php-socket:
