env:
  'vue/setup-compiler-macros': true

parserOptions:
  parser: '@typescript-eslint/parser'

rules:
  vue/require-default-prop: 'off'
  vue/multi-word-component-names: 'off'

extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'prettier'
